### ISSUE TITLE
关于CKA和CKAD证书有效期的问题

### ISSUE THREAD

**Issue by aladdinwang** [yuyicai/cka-ckad-exam-experience#1]
我看官网上说有效期是3年，如果超过有效期，是要重新考，还是可以自动续？
另外，优惠码似乎用不了

**Comment by yuyicai** [comment]
> 我看官网上说有效期是3年，如果超过有效期，是要重新考，还是可以自动续？
> 另外，优惠码似乎用不了
超期了要重考，不过你说你曾经考过了，也没人在意有效期吧
优惠的话，今天刚好网络星期一，全年优惠力度最大，打六折，cka一千两百多
https://training.linuxfoundation.cn/certificates/1

**Comment by aladdinwang** [comment]
cka, ckad有没有必要两个都考？
偏程序开发方向

**Comment by yuyicai** [comment]
> cka, ckad有没有必要两个都考？
> 偏程序开发方向

ckad可以看做cka的升级版，题目也都是操作类，与开发没太多关系（现在刚好打6折，一起考关系也不大，当时我看打折了两个一起考了）
（另外现在又出了一个cks，安全方向的，报名前提是先考cka）

不过做相关开发也要懂个操作的大概
对我个人而言，我觉得证书更大作用是找工作，对平时工作没什么帮助

另外我目前是做容器平台相关开发，平时可以交流交流

**Comment by yuyicai** [comment]
优惠信息 45折 课程➕考试（不算课程，只与考试费对比大概6折）
https://training.linuxfoundation.org/cyber-monday-2020/
